"""
WP-5.0 prototype generator: Khronos gl.xml -> C# bindings in a distinct namespace.

Scope is deliberately small. The point is not a finished generator; it is to answer one
question with a real number:

    if the generated names and shapes match Silk's, how many call-site lines change?

Harness design (the plan says designing it is part of this WP), and the three things that
had to be got right before either side compiled:

  1. Generated code goes in namespace `Karawan.Graphics.OpenGL`, never `Silk.NET.OpenGL`:
     emitting identical fully-qualified names while the Silk package is referenced would
     collide. It also must not be `Karawan.GL`, because a namespace segment `GL` shadows
     the `GL` class. Silk sidesteps this with namespace Silk.NET.OpenGL + class GL.
  2. The generated GL is an INSTANCE class with a GetApi factory, matching the shape the
     call sites are written against.
  3. OVERLOAD EXPANSION is the actual work. Splash.Silk calls BindBuffer with both
     BufferTargetARB and GLEnum, and GetInteger with both `out int` and `Span<int>`.
     gl.xml describes ONE C function per entry point; every one of these extra shapes is a
     policy decision the generator has to reproduce, and gl.xml cannot tell you about them.
     That is ADR 11c in miniature - see OVERLOADS below, which is hand-written because it
     has to be.
"""
import sys, xml.etree.ElementTree as ET

GL_XML, OUT = sys.argv[1], sys.argv[2]
NAMESPACE = "Karawan.Graphics.OpenGL"

COMMANDS = ["glBindBuffer", "glEnable", "glGetIntegerv", "glCreateProgram", "glCullFace"]
ENUM_GROUPS = ["BufferTargetARB", "EnableCap", "TriangleFace"]

# The GLEnum catch-all. Silk exposes every GL constant on one enum as well as on the
# specific groups; our code uses 43 of its members. Only the ones the sample needs are
# emitted here - a real generator would emit all 1380, which Silk does.
GLENUM_MEMBERS = ["GL_ACTIVE_TEXTURE", "GL_CURRENT_PROGRAM", "GL_ARRAY_BUFFER_BINDING",
                  "GL_VIEWPORT", "GL_ARRAY_BUFFER"]

# Hand-written, and that is the finding: gl.xml has no notion of these.
OVERLOADS = """
        // --- overload expansion -------------------------------------------------
        // None of the following is derivable from gl.xml. Each is a Silk API-policy
        // decision that call sites depend on, and each must be reproduced by hand or by
        // a hand-written rule. This is the cost ADR 11c says the ~500 LOC estimate misses.

        // BindBuffer, called with the catch-all enum as well as the typed one.
        public void BindBuffer(GLEnum target, uint buffer) => BindBuffer((BufferTargetARB)target, buffer);

        // Enable, same story.
        public void Enable(GLEnum cap) => Enable((EnableCap)cap);

        // GetInteger: Silk renames glGetIntegerv and offers an out-param form AND a
        // Span form. Two extra shapes and a rename, for one registry entry.
        public void GetInteger(GLEnum pname, out int data)
        {
            int v; GetIntegerv((uint)pname, &v); data = v;
        }

        public void GetInteger(GLEnum pname, Span<int> data)
        {
            fixed (int* p = data) { GetIntegerv((uint)pname, p); }
        }
"""

root = ET.parse(GL_XML).getroot()

enum_values, group_members = {}, {g: [] for g in ENUM_GROUPS}
for enums in root.findall('enums'):
    for e in enums.findall('enum'):
        n, v = e.get('name'), e.get('value')
        if n is None or v is None:
            continue
        enum_values[n] = v
        groups = (e.get('group') or '').split(',')
        for g in ENUM_GROUPS:
            if g in groups:
                group_members[g].append(n)

def cs_member(gl_name):
    s = gl_name[3:] if gl_name.startswith('GL_') else gl_name
    return ''.join(p.capitalize() for p in s.split('_'))

CTYPE = {'GLenum': 'uint', 'GLuint': 'uint', 'GLint': 'int', 'GLsizei': 'int',
         'GLboolean': 'bool', 'GLbitfield': 'uint', 'GLfloat': 'float',
         'GLdouble': 'double', 'void': 'void'}

commands = {}
for cmd in root.find('commands').findall('command'):
    proto = cmd.find('proto')
    name = proto.find('name').text
    if name not in COMMANDS:
        continue
    pt = proto.find('ptype')
    ret = pt.text if pt is not None else (proto.text or 'void').strip()
    params = []
    for p in cmd.findall('param'):
        t = p.find('ptype').text if p.find('ptype') is not None else 'GLint'
        params.append((p.find('name').text, t, '*' in ''.join(p.itertext()), p.get('group')))
    commands[name] = (ret, params)

def cs_type(t, ptr, grp):
    if ptr:
        return CTYPE.get(t, 'int') + '*'
    return grp if grp in ENUM_GROUPS else CTYPE.get(t, 'int')

L = ['// <auto-generated>',
     '//   WP-5.0 prototype, generated from the Khronos OpenGL registry (gl.xml).',
     f'//   Namespace {NAMESPACE} - deliberately not Silk.NET.OpenGL (collision) and not',
     '//   Karawan.GL (a namespace segment named GL shadows the GL class).',
     '// </auto-generated>',
     'using System;', 'using System.Runtime.InteropServices;', '',
     f'namespace {NAMESPACE}', '{']

for g in ENUM_GROUPS:
    L += [f'    public enum {g} : uint', '    {']
    seen = set()
    for m in sorted(set(group_members[g])):
        c = cs_member(m)
        if c not in seen:
            seen.add(c)
            L.append(f'        {c} = {enum_values[m]},')
    L += ['    }', '']

L += ['    /// <summary>Silk exposes every GL constant on one catch-all enum too.</summary>',
      '    public enum GLEnum : uint', '    {']
for m in GLENUM_MEMBERS:
    L.append(f'        {cs_member(m)} = {enum_values[m]},')
L += ['    }', '']

L += [f'    public unsafe partial class GL', '    {',
      '        private readonly Func<string, IntPtr> _getProc;',
      '        private GL(Func<string, IntPtr> getProc) { _getProc = getProc; }',
      '        public static GL GetApi(Func<string, IntPtr> getProc) => new GL(getProc);', '']

for gl_name in COMMANDS:
    ret, params = commands[gl_name]
    rcs = CTYPE.get(ret, 'void')
    sig = ', '.join(f'{cs_type(t, p, g)} {n}' for n, t, p, g in params)
    call = ', '.join(n for n, _, _, _ in params)
    m = gl_name[2:]
    L += [f'        private delegate {rcs} d_{m}({sig});',
          f'        private d_{m} _{m};',
          f'        public {rcs} {m}({sig})', '        {',
          f'            _{m} ??= Marshal.GetDelegateForFunctionPointer<d_{m}>(_getProc("{gl_name}"));',
          f'            {"return " if rcs != "void" else ""}_{m}({call});',
          '        }', '']

L.append(OVERLOADS)
L += ['    }', '}']

open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(L) + '\n')
members = sum(len(set(cs_member(m) for m in group_members[g])) for g in ENUM_GROUPS)
print(f'generated {OUT}')
print(f'  entry points from gl.xml : {len(commands)}/{len(COMMANDS)}')
print(f'  enum groups from gl.xml  : {len(ENUM_GROUPS)} ({members} members) + GLEnum ({len(GLENUM_MEMBERS)})')
print(f'  hand-written overloads   : 4  <-- not derivable from gl.xml')
print(f'  lines                    : {len(L)}')
