using System;
using System.Collections.Generic;
using System.Numerics;
using static engine.Logger;

namespace engine.world;


/**
 * Where a new game begins, in world coordinates.
 */
public readonly struct StartPose
{
    /**
     * ABSOLUTE world position. Named so, because the defect this type exists to end was
     * a caller adding the cluster's own origin to a value that already carried it.
     */
    public readonly Vector3 V3World;

    public readonly Quaternion QOrientation;

    public StartPose(in Vector3 v3World, in Quaternion qOrientation)
    {
        V3World = v3World;
        QOrientation = qOrientation;
    }
}


/**
 * The one answer to "where does a new game start".
 *
 * Two things ask: the player, through nogame.modules.playerhover.PlayerPosition, and the
 * coins a new game is seeded with, through nogame.world.DropCoinModule. They used to ask
 * differently - the player resolved a start estate, and the coins were a hard coded
 * column at world (164, 45..99, 137), 102 m away in plan from where the player actually
 * appears and 36 m below it - because the coin operator genuinely CANNOT read the player
 * position it would need: Saver.CallOnCreateNewGame runs against a brand new GameState
 * whose PlayerPosition is still Vector3.Zero, and that zero is what makes
 * PlayerPosition.GetPlayerPosition resolve a start lazily, later.
 *
 * So the resolution moved here, where both can reach it, and the answer is remembered:
 * ClusterDesc.FindStartPose looks for the first estate with no building on it, and
 * whether a given estate has one depends on which fragments have been generated by the
 * time it is asked. The coins are placed at create-new-game time and the player is placed
 * when the hover module sets up, so asking twice is asking at two different times. Once
 * resolved, everybody gets the same pose for the life of the session.
 */
public static class PlayerStart
{
    private static readonly engine.Dc _dc = engine.Dc.MetaGen;

    /**
     * Three metres toward the near edge of the estate, so the player does not appear
     * exactly on its centre.
     */
    public static readonly Vector3 Offset = new(0f, 0f, -3f);

    /**
     * How high above its city a new game begins. The player falls from here.
     */
    public const float DropHeight = 100f;

    /**
     * What a new game gets when there is no city at the world origin at all.
     */
    public static readonly StartPose NoCluster =
        new(new Vector3(0f, 200f, 0f), Quaternion.Identity);


    /**
     * The start on a named estate of a city, in world coordinates.
     *
     * The height is the city's average plus the drop, NOT the cluster's own Pos.Y plus
     * it: Pos.Y is the nominal elevation GenerateClustersOperator draws at random when it
     * lays the cities out, and AverageHeight - measured from the ground the city actually
     * stands on - is what replaces it. They agree for the start cluster, whose Pos.Y is
     * exactly 0.
     */
    public static StartPose OnEstate(in ClusterDesc clusterDesc, in Vector3 v3EstateCentre)
    {
        Vector3 v3ClusterStart = v3EstateCentre + Offset;

        Quaternion qStart;
        try
        {
            /*
             * Face the centre of the city. The direction is taken in the cluster's own
             * frame, which is the frame the centre is the origin of.
             */
            Vector3 vuZ = Vector3.Normalize(v3ClusterStart with { Y = 0f });
            qStart = Quaternion.CreateFromRotationMatrix(
                Matrix4x4.CreateWorld(Vector3.Zero, -vuZ, Vector3.UnitY));
        }
        catch (Exception e)
        {
            Error(_dc, $"Unable to face the centre of {clusterDesc.Name}: {e}");
            qStart = Quaternion.Identity;
        }

        if (!(Single.IsFinite(qStart.X) && Single.IsFinite(qStart.Y)
              && Single.IsFinite(qStart.Z) && Single.IsFinite(qStart.W)))
        {
            qStart = Quaternion.Identity;
        }

        return new StartPose(
            (v3ClusterStart + clusterDesc.Pos) with
            {
                Y = clusterDesc.AverageHeight + DropHeight
            },
            qStart);
    }


    /**
     * The start when a city has no free estate to offer: its centre, facing north.
     *
     * This branch used to return an ALREADY ABSOLUTE position out of a function whose
     * other branch returned a cluster relative one, and both call sites added the
     * cluster's origin to whatever came back - so a city with no free estate started the
     * player at twice its own position, a median 24 km from the city in the shipped
     * world. It is a fallback that no generated baseline reaches, which is why nothing
     * ever noticed.
     */
    public static StartPose AtClusterCentre(in ClusterDesc clusterDesc)
        => new(
            (clusterDesc.Pos + Offset) with
            {
                Y = clusterDesc.AverageHeight + DropHeight
            },
            Quaternion.Identity);


    /**
     * The start in a city whose blocks have already been traced: the first estate with
     * no building on it, and its centre if there is none.
     *
     * Separate from ClusterDesc.FindStartPose, which has to trigger street generation and
     * so needs ClusterStorage, MetaGen and the event queue out of the container. This
     * takes the quarter store it would produce, which StreetHarness builds from nothing,
     * so BOTH branches are driven over real generated cities rather than one of them
     * being reachable only by reading it.
     */
    public static StartPose PoseIn(in ClusterDesc clusterDesc, in streets.QuarterStore quarterStore)
    {
        foreach (var quarter in quarterStore.GetQuarters())
        {
            if (quarter.IsInvalid()) continue;
            foreach (var estate in quarter.GetEstates())
            {
                if (estate.GetBuildings().Count == 0)
                {
                    return OnEstate(clusterDesc, estate.GetCenter());
                }
            }
        }

        /*
         * If we didn't find anything, position ourselves in the centre of the cluster,
         * facing north.
         */
        return AtClusterCentre(clusterDesc);
    }


    private static readonly object _lo = new();
    private static StartPose? _pose = null;


    /**
     * Resolve, once, where this session's new game starts.
     */
    public static StartPose Find() => Once(_resolve);


    private static StartPose? _resolve()
    {
        ClusterDesc startCluster = I.Get<ClusterList>().GetClusterAt(Vector3.Zero);
        if (null == startCluster)
        {
            Error(_dc, $"No start cluster at the world origin, using {NoCluster.V3World}.");
            return null;
        }

        return startCluster.FindStartPose();
    }


    /**
     * Remember the first answer, and hand it to everyone afterwards.
     *
     * Separate from Find so that the remembering can be driven: Find itself needs the
     * cluster list, the cluster storage, MetaGen and the event queue out of the
     * container, and "it is asked twice and answers twice" is exactly the defect this
     * exists to prevent - the coins are placed at create-new-game time and the player
     * when the hover module sets up, and which estate is free depends on which fragments
     * have been generated in between.
     *
     * A resolver that cannot answer is NOT remembered: there may be no world yet, and
     * there may well be one by the time the next caller asks.
     */
    internal static StartPose Once(Func<StartPose?> resolve)
    {
        lock (_lo)
        {
            if (_pose.HasValue)
            {
                return _pose.Value;
            }
        }

        StartPose? fresh = resolve();
        if (!fresh.HasValue)
        {
            return NoCluster;
        }

        lock (_lo)
        {
            _pose ??= fresh;
            Trace(_dc, $"Start pose is {_pose.Value.V3World} {_pose.Value.QOrientation}");
            return _pose.Value;
        }
    }


    /**
     * Forget the resolved start pose. For tests and for starting a fresh game.
     */
    public static void Reset()
    {
        lock (_lo)
        {
            _pose = null;
        }
    }


    public const int NStartingItems = 19;
    public const float StartingItemSpacing = 3f;
    public const float StartingItemTopGap = 3f;


    /**
     * The column of items a new game is seeded with.
     *
     * The shipped column was 19 items at 3 m spacing hanging in the air, and it stays
     * that - only it now hangs under the point the player appears at, so the player falls
     * through it. The player starts DropHeight above the city and the column is 57 m
     * long, so it is entirely within the fall and entirely above the ground.
     */
    public static IEnumerable<Vector3> StartingItemColumn(Vector3 v3Start)
    {
        for (int i = 0; i < NStartingItems; ++i)
        {
            yield return v3Start with
            {
                Y = v3Start.Y - StartingItemTopGap - i * StartingItemSpacing
            };
        }
    }
}
