// <auto-generated>
//   Generated by docs/roadmap/proposed/wp-5.1/gen-trace.py from
//   Splash.GL/generated/GL.g.cs. DO NOT EDIT BY HAND - regenerate instead.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Runtime.InteropServices;

namespace Splash.Silk;

/// <summary>
/// Records every GL call, by interposing on the one function both bindings use to
/// resolve entry points. See gen-trace.py for why this seam and not a wrapper.
/// </summary>
public static class GLTrace
{
    private static readonly object _lo = new();
    private static List<string>? _sink;

    /// <summary>True while calls are being recorded. Checked on every GL call, so it
    /// is a plain field read and nothing more.</summary>
    public static bool IsRecording;

    /// <summary>Entry points the binding asked for that this tracer does not cover.
    /// They still work - the real pointer is handed through - but they are invisible,
    /// so a non-empty list means the comparison has a hole in it.</summary>
    public static readonly List<string> Untraced = new();

    public static int TracedCount => _thunks.Count;

    private static Func<string, IntPtr>? _real;
    private static readonly Dictionary<string, IntPtr> _thunks = new();
    private static readonly List<Delegate> _keepAlive = new();

    public static void Begin()
    {
        // Ordinals restart per capture, so each trace is self-contained. Otherwise the
        // numbering of the second anchor would depend on what the first one saw, and two
        // runs that captured different anchor sets could never be compared.
        lock (_lo) { _sink = new List<string>(65536); _canonMaps.Clear(); }
        IsRecording = true;
    }

    public static IReadOnlyList<string> End()
    {
        IsRecording = false;
        lock (_lo) { var s = _sink ?? new List<string>(); _sink = null; return s; }
    }

    /// <summary>
    /// Driver-assigned object name -> a stable ordinal, per KIND.
    /// </summary>
    /// <remarks>
    /// GL hands out object names in allocation order, so the same logical buffer is 24
    /// in one run and 31 in the next. Recording the raw value guarantees a diff that
    /// says nothing about the binding. Kinds are separate numbering spaces because a
    /// buffer 24 and a texture 24 are unrelated objects.
    /// </remarks>
    private static readonly Dictionary<string, Dictionary<uint, int>> _canonMaps = new();

    private static string _canon(string kind, uint raw)
    {
        // 0 is not an object, it is 'unbind'. It must stay 0 or every unbind reads as
        // a distinct object and the traces diverge on nothing.
        if (raw == 0) return kind + "#none";

        if (!_canonMaps.TryGetValue(kind, out var m))
        {
            m = new Dictionary<uint, int>();
            _canonMaps[kind] = m;
        }

        if (!m.TryGetValue(raw, out int ordinal))
        {
            ordinal = m.Count;
            m[raw] = ordinal;
        }

        return kind + "#" + ordinal;
    }

    private static void _rec(string line)
    {
        lock (_lo) { _sink?.Add(line); }
    }

    /// <summary>
    /// Wrap a backend's GetProcAddress. Entry points this tracer knows are answered
    /// with a thunk; anything else is passed straight through and noted in
    /// <see cref="Untraced"/>.
    /// </summary>
    public static Func<string, IntPtr> Wrap(Func<string, IntPtr> real)
    {
        _real = real;
        _register();
        return _lookup;
    }

    private static IntPtr _lookup(string name)
    {
        if (_thunks.TryGetValue(name, out IntPtr thunk)) return thunk;
        lock (_lo) { if (!Untraced.Contains(name)) Untraced.Add(name); }
        return _real!(name);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glActiveTexture(uint p0);
    private static D_glActiveTexture? _r_glActiveTexture;
    private static void _t_glActiveTexture(uint p0)
    {
        if (IsRecording) _rec("glActiveTexture(" + p0 + ")");
        _r_glActiveTexture!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glAttachShader(uint p0, uint p1);
    private static D_glAttachShader? _r_glAttachShader;
    private static void _t_glAttachShader(uint p0, uint p1)
    {
        if (IsRecording) _rec("glAttachShader(" + _canon("program", p0) + "," + _canon("shader", p1) + ")");
        _r_glAttachShader!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glBindBuffer(uint p0, uint p1);
    private static D_glBindBuffer? _r_glBindBuffer;
    private static void _t_glBindBuffer(uint p0, uint p1)
    {
        if (IsRecording) _rec("glBindBuffer(" + p0 + "," + _canon("buffer", p1) + ")");
        _r_glBindBuffer!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glBindBufferBase(uint p0, uint p1, uint p2);
    private static D_glBindBufferBase? _r_glBindBufferBase;
    private static void _t_glBindBufferBase(uint p0, uint p1, uint p2)
    {
        if (IsRecording) _rec("glBindBufferBase(" + p0 + "," + p1 + "," + _canon("buffer", p2) + ")");
        _r_glBindBufferBase!(p0, p1, p2);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glBindFramebuffer(uint p0, uint p1);
    private static D_glBindFramebuffer? _r_glBindFramebuffer;
    private static void _t_glBindFramebuffer(uint p0, uint p1)
    {
        if (IsRecording) _rec("glBindFramebuffer(" + p0 + "," + _canon("framebuffer", p1) + ")");
        _r_glBindFramebuffer!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glBindRenderbuffer(uint p0, uint p1);
    private static D_glBindRenderbuffer? _r_glBindRenderbuffer;
    private static void _t_glBindRenderbuffer(uint p0, uint p1)
    {
        if (IsRecording) _rec("glBindRenderbuffer(" + p0 + "," + _canon("renderbuffer", p1) + ")");
        _r_glBindRenderbuffer!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glBindSampler(uint p0, uint p1);
    private static D_glBindSampler? _r_glBindSampler;
    private static void _t_glBindSampler(uint p0, uint p1)
    {
        if (IsRecording) _rec("glBindSampler(" + p0 + "," + p1 + ")");
        _r_glBindSampler!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glBindTexture(uint p0, uint p1);
    private static D_glBindTexture? _r_glBindTexture;
    private static void _t_glBindTexture(uint p0, uint p1)
    {
        if (IsRecording) _rec("glBindTexture(" + p0 + "," + _canon("texture", p1) + ")");
        _r_glBindTexture!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glBindVertexArray(uint p0);
    private static D_glBindVertexArray? _r_glBindVertexArray;
    private static void _t_glBindVertexArray(uint p0)
    {
        if (IsRecording) _rec("glBindVertexArray(" + _canon("vao", p0) + ")");
        _r_glBindVertexArray!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glBlendEquation(uint p0);
    private static D_glBlendEquation? _r_glBlendEquation;
    private static void _t_glBlendEquation(uint p0)
    {
        if (IsRecording) _rec("glBlendEquation(" + p0 + ")");
        _r_glBlendEquation!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glBlendEquationSeparate(uint p0, uint p1);
    private static D_glBlendEquationSeparate? _r_glBlendEquationSeparate;
    private static void _t_glBlendEquationSeparate(uint p0, uint p1)
    {
        if (IsRecording) _rec("glBlendEquationSeparate(" + p0 + "," + p1 + ")");
        _r_glBlendEquationSeparate!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glBlendFuncSeparate(uint p0, uint p1, uint p2, uint p3);
    private static D_glBlendFuncSeparate? _r_glBlendFuncSeparate;
    private static void _t_glBlendFuncSeparate(uint p0, uint p1, uint p2, uint p3)
    {
        if (IsRecording) _rec("glBlendFuncSeparate(" + p0 + "," + p1 + "," + p2 + "," + p3 + ")");
        _r_glBlendFuncSeparate!(p0, p1, p2, p3);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glBufferData(uint p0, nuint p1, IntPtr p2, uint p3);
    private static D_glBufferData? _r_glBufferData;
    private static void _t_glBufferData(uint p0, nuint p1, IntPtr p2, uint p3)
    {
        if (IsRecording) _rec("glBufferData(" + p0 + "," + p1 + "," + (p2 == IntPtr.Zero ? "null" : "ptr") + "," + p3 + ")");
        _r_glBufferData!(p0, p1, p2, p3);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate uint D_glCheckFramebufferStatus(uint p0);
    private static D_glCheckFramebufferStatus? _r_glCheckFramebufferStatus;
    private static uint _t_glCheckFramebufferStatus(uint p0)
    {
        if (IsRecording) _rec("glCheckFramebufferStatus(" + p0 + ")");
        return _r_glCheckFramebufferStatus!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glClear(uint p0);
    private static D_glClear? _r_glClear;
    private static void _t_glClear(uint p0)
    {
        if (IsRecording) _rec("glClear(" + p0 + ")");
        _r_glClear!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glClearColor(float p0, float p1, float p2, float p3);
    private static D_glClearColor? _r_glClearColor;
    private static void _t_glClearColor(float p0, float p1, float p2, float p3)
    {
        if (IsRecording) _rec("glClearColor(" + p0.ToString("G9", CultureInfo.InvariantCulture) + "," + p1.ToString("G9", CultureInfo.InvariantCulture) + "," + p2.ToString("G9", CultureInfo.InvariantCulture) + "," + p3.ToString("G9", CultureInfo.InvariantCulture) + ")");
        _r_glClearColor!(p0, p1, p2, p3);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glClearDepthf(float p0);
    private static D_glClearDepthf? _r_glClearDepthf;
    private static void _t_glClearDepthf(float p0)
    {
        if (IsRecording) _rec("glClearDepthf(" + p0.ToString("G9", CultureInfo.InvariantCulture) + ")");
        _r_glClearDepthf!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glCompileShader(uint p0);
    private static D_glCompileShader? _r_glCompileShader;
    private static void _t_glCompileShader(uint p0)
    {
        if (IsRecording) _rec("glCompileShader(" + _canon("shader", p0) + ")");
        _r_glCompileShader!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate uint D_glCreateProgram();
    private static D_glCreateProgram? _r_glCreateProgram;
    private static uint _t_glCreateProgram()
    {
        if (IsRecording) _rec("glCreateProgram(" + "" + ")");
        return _r_glCreateProgram!();
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate uint D_glCreateShader(uint p0);
    private static D_glCreateShader? _r_glCreateShader;
    private static uint _t_glCreateShader(uint p0)
    {
        if (IsRecording) _rec("glCreateShader(" + p0 + ")");
        return _r_glCreateShader!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glCullFace(uint p0);
    private static D_glCullFace? _r_glCullFace;
    private static void _t_glCullFace(uint p0)
    {
        if (IsRecording) _rec("glCullFace(" + p0 + ")");
        _r_glCullFace!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glDeleteBuffers(int p0, IntPtr p1);
    private static D_glDeleteBuffers? _r_glDeleteBuffers;
    private static void _t_glDeleteBuffers(int p0, IntPtr p1)
    {
        if (IsRecording) _rec("glDeleteBuffers(" + p0 + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glDeleteBuffers!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glDeleteProgram(uint p0);
    private static D_glDeleteProgram? _r_glDeleteProgram;
    private static void _t_glDeleteProgram(uint p0)
    {
        if (IsRecording) _rec("glDeleteProgram(" + _canon("program", p0) + ")");
        _r_glDeleteProgram!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glDeleteShader(uint p0);
    private static D_glDeleteShader? _r_glDeleteShader;
    private static void _t_glDeleteShader(uint p0)
    {
        if (IsRecording) _rec("glDeleteShader(" + _canon("shader", p0) + ")");
        _r_glDeleteShader!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glDeleteTextures(int p0, IntPtr p1);
    private static D_glDeleteTextures? _r_glDeleteTextures;
    private static void _t_glDeleteTextures(int p0, IntPtr p1)
    {
        if (IsRecording) _rec("glDeleteTextures(" + p0 + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glDeleteTextures!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glDeleteVertexArrays(int p0, IntPtr p1);
    private static D_glDeleteVertexArrays? _r_glDeleteVertexArrays;
    private static void _t_glDeleteVertexArrays(int p0, IntPtr p1)
    {
        if (IsRecording) _rec("glDeleteVertexArrays(" + p0 + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glDeleteVertexArrays!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glDepthFunc(uint p0);
    private static D_glDepthFunc? _r_glDepthFunc;
    private static void _t_glDepthFunc(uint p0)
    {
        if (IsRecording) _rec("glDepthFunc(" + p0 + ")");
        _r_glDepthFunc!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glDepthMask(byte p0);
    private static D_glDepthMask? _r_glDepthMask;
    private static void _t_glDepthMask(byte p0)
    {
        if (IsRecording) _rec("glDepthMask(" + p0 + ")");
        _r_glDepthMask!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glDetachShader(uint p0, uint p1);
    private static D_glDetachShader? _r_glDetachShader;
    private static void _t_glDetachShader(uint p0, uint p1)
    {
        if (IsRecording) _rec("glDetachShader(" + p0 + "," + p1 + ")");
        _r_glDetachShader!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glDisable(uint p0);
    private static D_glDisable? _r_glDisable;
    private static void _t_glDisable(uint p0)
    {
        if (IsRecording) _rec("glDisable(" + p0 + ")");
        _r_glDisable!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glDrawBuffers(uint p0, IntPtr p1);
    private static D_glDrawBuffers? _r_glDrawBuffers;
    private static void _t_glDrawBuffers(uint p0, IntPtr p1)
    {
        if (IsRecording) _rec("glDrawBuffers(" + p0 + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glDrawBuffers!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glDrawElements(uint p0, uint p1, uint p2, IntPtr p3);
    private static D_glDrawElements? _r_glDrawElements;
    private static void _t_glDrawElements(uint p0, uint p1, uint p2, IntPtr p3)
    {
        if (IsRecording) _rec("glDrawElements(" + p0 + "," + p1 + "," + p2 + "," + (p3 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glDrawElements!(p0, p1, p2, p3);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glDrawElementsBaseVertex(uint p0, uint p1, uint p2, IntPtr p3, int p4);
    private static D_glDrawElementsBaseVertex? _r_glDrawElementsBaseVertex;
    private static void _t_glDrawElementsBaseVertex(uint p0, uint p1, uint p2, IntPtr p3, int p4)
    {
        if (IsRecording) _rec("glDrawElementsBaseVertex(" + p0 + "," + p1 + "," + p2 + "," + (p3 == IntPtr.Zero ? "null" : "ptr") + "," + p4 + ")");
        _r_glDrawElementsBaseVertex!(p0, p1, p2, p3, p4);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glDrawElementsInstanced(uint p0, uint p1, uint p2, IntPtr p3, uint p4);
    private static D_glDrawElementsInstanced? _r_glDrawElementsInstanced;
    private static void _t_glDrawElementsInstanced(uint p0, uint p1, uint p2, IntPtr p3, uint p4)
    {
        if (IsRecording) _rec("glDrawElementsInstanced(" + p0 + "," + p1 + "," + p2 + "," + (p3 == IntPtr.Zero ? "null" : "ptr") + "," + p4 + ")");
        _r_glDrawElementsInstanced!(p0, p1, p2, p3, p4);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glEnable(uint p0);
    private static D_glEnable? _r_glEnable;
    private static void _t_glEnable(uint p0)
    {
        if (IsRecording) _rec("glEnable(" + p0 + ")");
        _r_glEnable!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glEnableVertexAttribArray(uint p0);
    private static D_glEnableVertexAttribArray? _r_glEnableVertexAttribArray;
    private static void _t_glEnableVertexAttribArray(uint p0)
    {
        if (IsRecording) _rec("glEnableVertexAttribArray(" + p0 + ")");
        _r_glEnableVertexAttribArray!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glFramebufferRenderbuffer(uint p0, uint p1, uint p2, uint p3);
    private static D_glFramebufferRenderbuffer? _r_glFramebufferRenderbuffer;
    private static void _t_glFramebufferRenderbuffer(uint p0, uint p1, uint p2, uint p3)
    {
        if (IsRecording) _rec("glFramebufferRenderbuffer(" + p0 + "," + p1 + "," + p2 + "," + _canon("renderbuffer", p3) + ")");
        _r_glFramebufferRenderbuffer!(p0, p1, p2, p3);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glFramebufferTexture(uint p0, uint p1, uint p2, int p3);
    private static D_glFramebufferTexture? _r_glFramebufferTexture;
    private static void _t_glFramebufferTexture(uint p0, uint p1, uint p2, int p3)
    {
        if (IsRecording) _rec("glFramebufferTexture(" + p0 + "," + p1 + "," + p2 + "," + p3 + ")");
        _r_glFramebufferTexture!(p0, p1, p2, p3);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glFrontFace(uint p0);
    private static D_glFrontFace? _r_glFrontFace;
    private static void _t_glFrontFace(uint p0)
    {
        if (IsRecording) _rec("glFrontFace(" + p0 + ")");
        _r_glFrontFace!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glGenBuffers(int p0, IntPtr p1);
    private static D_glGenBuffers? _r_glGenBuffers;
    private static void _t_glGenBuffers(int p0, IntPtr p1)
    {
        if (IsRecording) _rec("glGenBuffers(" + p0 + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glGenBuffers!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glGenFramebuffers(uint p0, IntPtr p1);
    private static D_glGenFramebuffers? _r_glGenFramebuffers;
    private static void _t_glGenFramebuffers(uint p0, IntPtr p1)
    {
        if (IsRecording) _rec("glGenFramebuffers(" + p0 + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glGenFramebuffers!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glGenRenderbuffers(uint p0, IntPtr p1);
    private static D_glGenRenderbuffers? _r_glGenRenderbuffers;
    private static void _t_glGenRenderbuffers(uint p0, IntPtr p1)
    {
        if (IsRecording) _rec("glGenRenderbuffers(" + p0 + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glGenRenderbuffers!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glGenTextures(int p0, IntPtr p1);
    private static D_glGenTextures? _r_glGenTextures;
    private static void _t_glGenTextures(int p0, IntPtr p1)
    {
        if (IsRecording) _rec("glGenTextures(" + p0 + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glGenTextures!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glGenVertexArrays(int p0, IntPtr p1);
    private static D_glGenVertexArrays? _r_glGenVertexArrays;
    private static void _t_glGenVertexArrays(int p0, IntPtr p1)
    {
        if (IsRecording) _rec("glGenVertexArrays(" + p0 + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glGenVertexArrays!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glGenerateMipmap(uint p0);
    private static D_glGenerateMipmap? _r_glGenerateMipmap;
    private static void _t_glGenerateMipmap(uint p0)
    {
        if (IsRecording) _rec("glGenerateMipmap(" + p0 + ")");
        _r_glGenerateMipmap!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate int D_glGetAttribLocation(uint p0, IntPtr p1);
    private static D_glGetAttribLocation? _r_glGetAttribLocation;
    private static int _t_glGetAttribLocation(uint p0, IntPtr p1)
    {
        if (IsRecording) _rec("glGetAttribLocation(" + _canon("program", p0) + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        return _r_glGetAttribLocation!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glGetBooleanv(uint p0, IntPtr p1);
    private static D_glGetBooleanv? _r_glGetBooleanv;
    private static void _t_glGetBooleanv(uint p0, IntPtr p1)
    {
        if (IsRecording) _rec("glGetBooleanv(" + p0 + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glGetBooleanv!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate uint D_glGetError();
    private static D_glGetError? _r_glGetError;
    private static uint _t_glGetError()
    {
        if (IsRecording) _rec("glGetError(" + "" + ")");
        return _r_glGetError!();
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glGetFloatv(uint p0, IntPtr p1);
    private static D_glGetFloatv? _r_glGetFloatv;
    private static void _t_glGetFloatv(uint p0, IntPtr p1)
    {
        if (IsRecording) _rec("glGetFloatv(" + p0 + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glGetFloatv!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glGetIntegerv(uint p0, IntPtr p1);
    private static D_glGetIntegerv? _r_glGetIntegerv;
    private static void _t_glGetIntegerv(uint p0, IntPtr p1)
    {
        if (IsRecording) _rec("glGetIntegerv(" + p0 + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glGetIntegerv!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glGetProgramInfoLog(uint p0, int p1, IntPtr p2, IntPtr p3);
    private static D_glGetProgramInfoLog? _r_glGetProgramInfoLog;
    private static void _t_glGetProgramInfoLog(uint p0, int p1, IntPtr p2, IntPtr p3)
    {
        if (IsRecording) _rec("glGetProgramInfoLog(" + _canon("program", p0) + "," + p1 + "," + (p2 == IntPtr.Zero ? "null" : "ptr") + "," + (p3 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glGetProgramInfoLog!(p0, p1, p2, p3);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glGetProgramiv(uint p0, uint p1, IntPtr p2);
    private static D_glGetProgramiv? _r_glGetProgramiv;
    private static void _t_glGetProgramiv(uint p0, uint p1, IntPtr p2)
    {
        if (IsRecording) _rec("glGetProgramiv(" + _canon("program", p0) + "," + p1 + "," + (p2 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glGetProgramiv!(p0, p1, p2);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glGetShaderInfoLog(uint p0, int p1, IntPtr p2, IntPtr p3);
    private static D_glGetShaderInfoLog? _r_glGetShaderInfoLog;
    private static void _t_glGetShaderInfoLog(uint p0, int p1, IntPtr p2, IntPtr p3)
    {
        if (IsRecording) _rec("glGetShaderInfoLog(" + _canon("shader", p0) + "," + p1 + "," + (p2 == IntPtr.Zero ? "null" : "ptr") + "," + (p3 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glGetShaderInfoLog!(p0, p1, p2, p3);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glGetShaderiv(uint p0, uint p1, IntPtr p2);
    private static D_glGetShaderiv? _r_glGetShaderiv;
    private static void _t_glGetShaderiv(uint p0, uint p1, IntPtr p2)
    {
        if (IsRecording) _rec("glGetShaderiv(" + _canon("shader", p0) + "," + p1 + "," + (p2 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glGetShaderiv!(p0, p1, p2);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate IntPtr D_glGetString(uint p0);
    private static D_glGetString? _r_glGetString;
    private static IntPtr _t_glGetString(uint p0)
    {
        if (IsRecording) _rec("glGetString(" + p0 + ")");
        return _r_glGetString!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate uint D_glGetUniformBlockIndex(uint p0, IntPtr p1);
    private static D_glGetUniformBlockIndex? _r_glGetUniformBlockIndex;
    private static uint _t_glGetUniformBlockIndex(uint p0, IntPtr p1)
    {
        if (IsRecording) _rec("glGetUniformBlockIndex(" + _canon("program", p0) + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        return _r_glGetUniformBlockIndex!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate int D_glGetUniformLocation(uint p0, IntPtr p1);
    private static D_glGetUniformLocation? _r_glGetUniformLocation;
    private static int _t_glGetUniformLocation(uint p0, IntPtr p1)
    {
        if (IsRecording) _rec("glGetUniformLocation(" + _canon("program", p0) + "," + (p1 == IntPtr.Zero ? "null" : "ptr") + ")");
        return _r_glGetUniformLocation!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate byte D_glIsEnabled(uint p0);
    private static D_glIsEnabled? _r_glIsEnabled;
    private static byte _t_glIsEnabled(uint p0)
    {
        if (IsRecording) _rec("glIsEnabled(" + p0 + ")");
        return _r_glIsEnabled!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glLinkProgram(uint p0);
    private static D_glLinkProgram? _r_glLinkProgram;
    private static void _t_glLinkProgram(uint p0)
    {
        if (IsRecording) _rec("glLinkProgram(" + _canon("program", p0) + ")");
        _r_glLinkProgram!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glPixelStorei(uint p0, int p1);
    private static D_glPixelStorei? _r_glPixelStorei;
    private static void _t_glPixelStorei(uint p0, int p1)
    {
        if (IsRecording) _rec("glPixelStorei(" + p0 + "," + p1 + ")");
        _r_glPixelStorei!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glPolygonMode(uint p0, uint p1);
    private static D_glPolygonMode? _r_glPolygonMode;
    private static void _t_glPolygonMode(uint p0, uint p1)
    {
        if (IsRecording) _rec("glPolygonMode(" + p0 + "," + p1 + ")");
        _r_glPolygonMode!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glRenderbufferStorage(uint p0, uint p1, uint p2, uint p3);
    private static D_glRenderbufferStorage? _r_glRenderbufferStorage;
    private static void _t_glRenderbufferStorage(uint p0, uint p1, uint p2, uint p3)
    {
        if (IsRecording) _rec("glRenderbufferStorage(" + p0 + "," + p1 + "," + p2 + "," + p3 + ")");
        _r_glRenderbufferStorage!(p0, p1, p2, p3);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glScissor(int p0, int p1, uint p2, uint p3);
    private static D_glScissor? _r_glScissor;
    private static void _t_glScissor(int p0, int p1, uint p2, uint p3)
    {
        if (IsRecording) _rec("glScissor(" + p0 + "," + p1 + "," + p2 + "," + p3 + ")");
        _r_glScissor!(p0, p1, p2, p3);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glShaderSource(uint p0, int p1, IntPtr p2, IntPtr p3);
    private static D_glShaderSource? _r_glShaderSource;
    private static void _t_glShaderSource(uint p0, int p1, IntPtr p2, IntPtr p3)
    {
        if (IsRecording) _rec("glShaderSource(" + _canon("shader", p0) + "," + p1 + "," + (p2 == IntPtr.Zero ? "null" : "ptr") + "," + (p3 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glShaderSource!(p0, p1, p2, p3);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glTexImage2D(uint p0, int p1, int p2, uint p3, uint p4, int p5, uint p6, uint p7, IntPtr p8);
    private static D_glTexImage2D? _r_glTexImage2D;
    private static void _t_glTexImage2D(uint p0, int p1, int p2, uint p3, uint p4, int p5, uint p6, uint p7, IntPtr p8)
    {
        if (IsRecording) _rec("glTexImage2D(" + p0 + "," + p1 + "," + p2 + "," + p3 + "," + p4 + "," + p5 + "," + p6 + "," + p7 + "," + (p8 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glTexImage2D!(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glTexParameterIiv(uint p0, uint p1, IntPtr p2);
    private static D_glTexParameterIiv? _r_glTexParameterIiv;
    private static void _t_glTexParameterIiv(uint p0, uint p1, IntPtr p2)
    {
        if (IsRecording) _rec("glTexParameterIiv(" + p0 + "," + p1 + "," + (p2 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glTexParameterIiv!(p0, p1, p2);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glTexParameterIuiv(uint p0, uint p1, IntPtr p2);
    private static D_glTexParameterIuiv? _r_glTexParameterIuiv;
    private static void _t_glTexParameterIuiv(uint p0, uint p1, IntPtr p2)
    {
        if (IsRecording) _rec("glTexParameterIuiv(" + p0 + "," + p1 + "," + (p2 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glTexParameterIuiv!(p0, p1, p2);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glTexParameterf(uint p0, uint p1, float p2);
    private static D_glTexParameterf? _r_glTexParameterf;
    private static void _t_glTexParameterf(uint p0, uint p1, float p2)
    {
        if (IsRecording) _rec("glTexParameterf(" + p0 + "," + p1 + "," + p2.ToString("G9", CultureInfo.InvariantCulture) + ")");
        _r_glTexParameterf!(p0, p1, p2);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glTexParameteri(uint p0, uint p1, int p2);
    private static D_glTexParameteri? _r_glTexParameteri;
    private static void _t_glTexParameteri(uint p0, uint p1, int p2)
    {
        if (IsRecording) _rec("glTexParameteri(" + p0 + "," + p1 + "," + p2 + ")");
        _r_glTexParameteri!(p0, p1, p2);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glTexStorage2D(uint p0, uint p1, uint p2, uint p3, uint p4);
    private static D_glTexStorage2D? _r_glTexStorage2D;
    private static void _t_glTexStorage2D(uint p0, uint p1, uint p2, uint p3, uint p4)
    {
        if (IsRecording) _rec("glTexStorage2D(" + p0 + "," + p1 + "," + p2 + "," + p3 + "," + p4 + ")");
        _r_glTexStorage2D!(p0, p1, p2, p3, p4);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glTexSubImage2D(uint p0, int p1, int p2, int p3, uint p4, uint p5, uint p6, uint p7, IntPtr p8);
    private static D_glTexSubImage2D? _r_glTexSubImage2D;
    private static void _t_glTexSubImage2D(uint p0, int p1, int p2, int p3, uint p4, uint p5, uint p6, uint p7, IntPtr p8)
    {
        if (IsRecording) _rec("glTexSubImage2D(" + p0 + "," + p1 + "," + p2 + "," + p3 + "," + p4 + "," + p5 + "," + p6 + "," + p7 + "," + (p8 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glTexSubImage2D!(p0, p1, p2, p3, p4, p5, p6, p7, p8);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glUniform1f(int p0, float p1);
    private static D_glUniform1f? _r_glUniform1f;
    private static void _t_glUniform1f(int p0, float p1)
    {
        if (IsRecording) _rec("glUniform1f(" + p0 + "," + p1.ToString("G9", CultureInfo.InvariantCulture) + ")");
        _r_glUniform1f!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glUniform1i(int p0, int p1);
    private static D_glUniform1i? _r_glUniform1i;
    private static void _t_glUniform1i(int p0, int p1)
    {
        if (IsRecording) _rec("glUniform1i(" + p0 + "," + p1 + ")");
        _r_glUniform1i!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glUniform1ui(int p0, uint p1);
    private static D_glUniform1ui? _r_glUniform1ui;
    private static void _t_glUniform1ui(int p0, uint p1)
    {
        if (IsRecording) _rec("glUniform1ui(" + p0 + "," + p1 + ")");
        _r_glUniform1ui!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glUniform3f(int p0, float p1, float p2, float p3);
    private static D_glUniform3f? _r_glUniform3f;
    private static void _t_glUniform3f(int p0, float p1, float p2, float p3)
    {
        if (IsRecording) _rec("glUniform3f(" + p0 + "," + p1.ToString("G9", CultureInfo.InvariantCulture) + "," + p2.ToString("G9", CultureInfo.InvariantCulture) + "," + p3.ToString("G9", CultureInfo.InvariantCulture) + ")");
        _r_glUniform3f!(p0, p1, p2, p3);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glUniform4f(int p0, float p1, float p2, float p3, float p4);
    private static D_glUniform4f? _r_glUniform4f;
    private static void _t_glUniform4f(int p0, float p1, float p2, float p3, float p4)
    {
        if (IsRecording) _rec("glUniform4f(" + p0 + "," + p1.ToString("G9", CultureInfo.InvariantCulture) + "," + p2.ToString("G9", CultureInfo.InvariantCulture) + "," + p3.ToString("G9", CultureInfo.InvariantCulture) + "," + p4.ToString("G9", CultureInfo.InvariantCulture) + ")");
        _r_glUniform4f!(p0, p1, p2, p3, p4);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glUniformMatrix4fv(int p0, int p1, byte p2, IntPtr p3);
    private static D_glUniformMatrix4fv? _r_glUniformMatrix4fv;
    private static void _t_glUniformMatrix4fv(int p0, int p1, byte p2, IntPtr p3)
    {
        if (IsRecording) _rec("glUniformMatrix4fv(" + p0 + "," + p1 + "," + p2 + "," + (p3 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glUniformMatrix4fv!(p0, p1, p2, p3);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glUseProgram(uint p0);
    private static D_glUseProgram? _r_glUseProgram;
    private static void _t_glUseProgram(uint p0)
    {
        if (IsRecording) _rec("glUseProgram(" + _canon("program", p0) + ")");
        _r_glUseProgram!(p0);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glVertexAttribDivisor(uint p0, uint p1);
    private static D_glVertexAttribDivisor? _r_glVertexAttribDivisor;
    private static void _t_glVertexAttribDivisor(uint p0, uint p1)
    {
        if (IsRecording) _rec("glVertexAttribDivisor(" + p0 + "," + p1 + ")");
        _r_glVertexAttribDivisor!(p0, p1);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glVertexAttribIPointer(uint p0, int p1, uint p2, uint p3, IntPtr p4);
    private static D_glVertexAttribIPointer? _r_glVertexAttribIPointer;
    private static void _t_glVertexAttribIPointer(uint p0, int p1, uint p2, uint p3, IntPtr p4)
    {
        if (IsRecording) _rec("glVertexAttribIPointer(" + p0 + "," + p1 + "," + p2 + "," + p3 + "," + (p4 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glVertexAttribIPointer!(p0, p1, p2, p3, p4);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glVertexAttribPointer(uint p0, int p1, uint p2, byte p3, uint p4, IntPtr p5);
    private static D_glVertexAttribPointer? _r_glVertexAttribPointer;
    private static void _t_glVertexAttribPointer(uint p0, int p1, uint p2, byte p3, uint p4, IntPtr p5)
    {
        if (IsRecording) _rec("glVertexAttribPointer(" + p0 + "," + p1 + "," + p2 + "," + p3 + "," + p4 + "," + (p5 == IntPtr.Zero ? "null" : "ptr") + ")");
        _r_glVertexAttribPointer!(p0, p1, p2, p3, p4, p5);
    }

    [UnmanagedFunctionPointer(CallingConvention.Winapi)]
    private delegate void D_glViewport(int p0, int p1, uint p2, uint p3);
    private static D_glViewport? _r_glViewport;
    private static void _t_glViewport(int p0, int p1, uint p2, uint p3)
    {
        if (IsRecording) _rec("glViewport(" + p0 + "," + p1 + "," + p2 + "," + p3 + ")");
        _r_glViewport!(p0, p1, p2, p3);
    }

    private static void _register()
    {
        _thunks.Clear();
        _keepAlive.Clear();
        _bind("glActiveTexture", p => _r_glActiveTexture = Marshal.GetDelegateForFunctionPointer<D_glActiveTexture>(p), new D_glActiveTexture(_t_glActiveTexture));
        _bind("glAttachShader", p => _r_glAttachShader = Marshal.GetDelegateForFunctionPointer<D_glAttachShader>(p), new D_glAttachShader(_t_glAttachShader));
        _bind("glBindBuffer", p => _r_glBindBuffer = Marshal.GetDelegateForFunctionPointer<D_glBindBuffer>(p), new D_glBindBuffer(_t_glBindBuffer));
        _bind("glBindBufferBase", p => _r_glBindBufferBase = Marshal.GetDelegateForFunctionPointer<D_glBindBufferBase>(p), new D_glBindBufferBase(_t_glBindBufferBase));
        _bind("glBindFramebuffer", p => _r_glBindFramebuffer = Marshal.GetDelegateForFunctionPointer<D_glBindFramebuffer>(p), new D_glBindFramebuffer(_t_glBindFramebuffer));
        _bind("glBindRenderbuffer", p => _r_glBindRenderbuffer = Marshal.GetDelegateForFunctionPointer<D_glBindRenderbuffer>(p), new D_glBindRenderbuffer(_t_glBindRenderbuffer));
        _bind("glBindSampler", p => _r_glBindSampler = Marshal.GetDelegateForFunctionPointer<D_glBindSampler>(p), new D_glBindSampler(_t_glBindSampler));
        _bind("glBindTexture", p => _r_glBindTexture = Marshal.GetDelegateForFunctionPointer<D_glBindTexture>(p), new D_glBindTexture(_t_glBindTexture));
        _bind("glBindVertexArray", p => _r_glBindVertexArray = Marshal.GetDelegateForFunctionPointer<D_glBindVertexArray>(p), new D_glBindVertexArray(_t_glBindVertexArray));
        _bind("glBlendEquation", p => _r_glBlendEquation = Marshal.GetDelegateForFunctionPointer<D_glBlendEquation>(p), new D_glBlendEquation(_t_glBlendEquation));
        _bind("glBlendEquationSeparate", p => _r_glBlendEquationSeparate = Marshal.GetDelegateForFunctionPointer<D_glBlendEquationSeparate>(p), new D_glBlendEquationSeparate(_t_glBlendEquationSeparate));
        _bind("glBlendFuncSeparate", p => _r_glBlendFuncSeparate = Marshal.GetDelegateForFunctionPointer<D_glBlendFuncSeparate>(p), new D_glBlendFuncSeparate(_t_glBlendFuncSeparate));
        _bind("glBufferData", p => _r_glBufferData = Marshal.GetDelegateForFunctionPointer<D_glBufferData>(p), new D_glBufferData(_t_glBufferData));
        _bind("glCheckFramebufferStatus", p => _r_glCheckFramebufferStatus = Marshal.GetDelegateForFunctionPointer<D_glCheckFramebufferStatus>(p), new D_glCheckFramebufferStatus(_t_glCheckFramebufferStatus));
        _bind("glClear", p => _r_glClear = Marshal.GetDelegateForFunctionPointer<D_glClear>(p), new D_glClear(_t_glClear));
        _bind("glClearColor", p => _r_glClearColor = Marshal.GetDelegateForFunctionPointer<D_glClearColor>(p), new D_glClearColor(_t_glClearColor));
        _bind("glClearDepthf", p => _r_glClearDepthf = Marshal.GetDelegateForFunctionPointer<D_glClearDepthf>(p), new D_glClearDepthf(_t_glClearDepthf));
        _bind("glCompileShader", p => _r_glCompileShader = Marshal.GetDelegateForFunctionPointer<D_glCompileShader>(p), new D_glCompileShader(_t_glCompileShader));
        _bind("glCreateProgram", p => _r_glCreateProgram = Marshal.GetDelegateForFunctionPointer<D_glCreateProgram>(p), new D_glCreateProgram(_t_glCreateProgram));
        _bind("glCreateShader", p => _r_glCreateShader = Marshal.GetDelegateForFunctionPointer<D_glCreateShader>(p), new D_glCreateShader(_t_glCreateShader));
        _bind("glCullFace", p => _r_glCullFace = Marshal.GetDelegateForFunctionPointer<D_glCullFace>(p), new D_glCullFace(_t_glCullFace));
        _bind("glDeleteBuffers", p => _r_glDeleteBuffers = Marshal.GetDelegateForFunctionPointer<D_glDeleteBuffers>(p), new D_glDeleteBuffers(_t_glDeleteBuffers));
        _bind("glDeleteProgram", p => _r_glDeleteProgram = Marshal.GetDelegateForFunctionPointer<D_glDeleteProgram>(p), new D_glDeleteProgram(_t_glDeleteProgram));
        _bind("glDeleteShader", p => _r_glDeleteShader = Marshal.GetDelegateForFunctionPointer<D_glDeleteShader>(p), new D_glDeleteShader(_t_glDeleteShader));
        _bind("glDeleteTextures", p => _r_glDeleteTextures = Marshal.GetDelegateForFunctionPointer<D_glDeleteTextures>(p), new D_glDeleteTextures(_t_glDeleteTextures));
        _bind("glDeleteVertexArrays", p => _r_glDeleteVertexArrays = Marshal.GetDelegateForFunctionPointer<D_glDeleteVertexArrays>(p), new D_glDeleteVertexArrays(_t_glDeleteVertexArrays));
        _bind("glDepthFunc", p => _r_glDepthFunc = Marshal.GetDelegateForFunctionPointer<D_glDepthFunc>(p), new D_glDepthFunc(_t_glDepthFunc));
        _bind("glDepthMask", p => _r_glDepthMask = Marshal.GetDelegateForFunctionPointer<D_glDepthMask>(p), new D_glDepthMask(_t_glDepthMask));
        _bind("glDetachShader", p => _r_glDetachShader = Marshal.GetDelegateForFunctionPointer<D_glDetachShader>(p), new D_glDetachShader(_t_glDetachShader));
        _bind("glDisable", p => _r_glDisable = Marshal.GetDelegateForFunctionPointer<D_glDisable>(p), new D_glDisable(_t_glDisable));
        _bind("glDrawBuffers", p => _r_glDrawBuffers = Marshal.GetDelegateForFunctionPointer<D_glDrawBuffers>(p), new D_glDrawBuffers(_t_glDrawBuffers));
        _bind("glDrawElements", p => _r_glDrawElements = Marshal.GetDelegateForFunctionPointer<D_glDrawElements>(p), new D_glDrawElements(_t_glDrawElements));
        _bind("glDrawElementsBaseVertex", p => _r_glDrawElementsBaseVertex = Marshal.GetDelegateForFunctionPointer<D_glDrawElementsBaseVertex>(p), new D_glDrawElementsBaseVertex(_t_glDrawElementsBaseVertex));
        _bind("glDrawElementsInstanced", p => _r_glDrawElementsInstanced = Marshal.GetDelegateForFunctionPointer<D_glDrawElementsInstanced>(p), new D_glDrawElementsInstanced(_t_glDrawElementsInstanced));
        _bind("glEnable", p => _r_glEnable = Marshal.GetDelegateForFunctionPointer<D_glEnable>(p), new D_glEnable(_t_glEnable));
        _bind("glEnableVertexAttribArray", p => _r_glEnableVertexAttribArray = Marshal.GetDelegateForFunctionPointer<D_glEnableVertexAttribArray>(p), new D_glEnableVertexAttribArray(_t_glEnableVertexAttribArray));
        _bind("glFramebufferRenderbuffer", p => _r_glFramebufferRenderbuffer = Marshal.GetDelegateForFunctionPointer<D_glFramebufferRenderbuffer>(p), new D_glFramebufferRenderbuffer(_t_glFramebufferRenderbuffer));
        _bind("glFramebufferTexture", p => _r_glFramebufferTexture = Marshal.GetDelegateForFunctionPointer<D_glFramebufferTexture>(p), new D_glFramebufferTexture(_t_glFramebufferTexture));
        _bind("glFrontFace", p => _r_glFrontFace = Marshal.GetDelegateForFunctionPointer<D_glFrontFace>(p), new D_glFrontFace(_t_glFrontFace));
        _bind("glGenBuffers", p => _r_glGenBuffers = Marshal.GetDelegateForFunctionPointer<D_glGenBuffers>(p), new D_glGenBuffers(_t_glGenBuffers));
        _bind("glGenFramebuffers", p => _r_glGenFramebuffers = Marshal.GetDelegateForFunctionPointer<D_glGenFramebuffers>(p), new D_glGenFramebuffers(_t_glGenFramebuffers));
        _bind("glGenRenderbuffers", p => _r_glGenRenderbuffers = Marshal.GetDelegateForFunctionPointer<D_glGenRenderbuffers>(p), new D_glGenRenderbuffers(_t_glGenRenderbuffers));
        _bind("glGenTextures", p => _r_glGenTextures = Marshal.GetDelegateForFunctionPointer<D_glGenTextures>(p), new D_glGenTextures(_t_glGenTextures));
        _bind("glGenVertexArrays", p => _r_glGenVertexArrays = Marshal.GetDelegateForFunctionPointer<D_glGenVertexArrays>(p), new D_glGenVertexArrays(_t_glGenVertexArrays));
        _bind("glGenerateMipmap", p => _r_glGenerateMipmap = Marshal.GetDelegateForFunctionPointer<D_glGenerateMipmap>(p), new D_glGenerateMipmap(_t_glGenerateMipmap));
        _bind("glGetAttribLocation", p => _r_glGetAttribLocation = Marshal.GetDelegateForFunctionPointer<D_glGetAttribLocation>(p), new D_glGetAttribLocation(_t_glGetAttribLocation));
        _bind("glGetBooleanv", p => _r_glGetBooleanv = Marshal.GetDelegateForFunctionPointer<D_glGetBooleanv>(p), new D_glGetBooleanv(_t_glGetBooleanv));
        _bind("glGetError", p => _r_glGetError = Marshal.GetDelegateForFunctionPointer<D_glGetError>(p), new D_glGetError(_t_glGetError));
        _bind("glGetFloatv", p => _r_glGetFloatv = Marshal.GetDelegateForFunctionPointer<D_glGetFloatv>(p), new D_glGetFloatv(_t_glGetFloatv));
        _bind("glGetIntegerv", p => _r_glGetIntegerv = Marshal.GetDelegateForFunctionPointer<D_glGetIntegerv>(p), new D_glGetIntegerv(_t_glGetIntegerv));
        _bind("glGetProgramInfoLog", p => _r_glGetProgramInfoLog = Marshal.GetDelegateForFunctionPointer<D_glGetProgramInfoLog>(p), new D_glGetProgramInfoLog(_t_glGetProgramInfoLog));
        _bind("glGetProgramiv", p => _r_glGetProgramiv = Marshal.GetDelegateForFunctionPointer<D_glGetProgramiv>(p), new D_glGetProgramiv(_t_glGetProgramiv));
        _bind("glGetShaderInfoLog", p => _r_glGetShaderInfoLog = Marshal.GetDelegateForFunctionPointer<D_glGetShaderInfoLog>(p), new D_glGetShaderInfoLog(_t_glGetShaderInfoLog));
        _bind("glGetShaderiv", p => _r_glGetShaderiv = Marshal.GetDelegateForFunctionPointer<D_glGetShaderiv>(p), new D_glGetShaderiv(_t_glGetShaderiv));
        _bind("glGetString", p => _r_glGetString = Marshal.GetDelegateForFunctionPointer<D_glGetString>(p), new D_glGetString(_t_glGetString));
        _bind("glGetUniformBlockIndex", p => _r_glGetUniformBlockIndex = Marshal.GetDelegateForFunctionPointer<D_glGetUniformBlockIndex>(p), new D_glGetUniformBlockIndex(_t_glGetUniformBlockIndex));
        _bind("glGetUniformLocation", p => _r_glGetUniformLocation = Marshal.GetDelegateForFunctionPointer<D_glGetUniformLocation>(p), new D_glGetUniformLocation(_t_glGetUniformLocation));
        _bind("glIsEnabled", p => _r_glIsEnabled = Marshal.GetDelegateForFunctionPointer<D_glIsEnabled>(p), new D_glIsEnabled(_t_glIsEnabled));
        _bind("glLinkProgram", p => _r_glLinkProgram = Marshal.GetDelegateForFunctionPointer<D_glLinkProgram>(p), new D_glLinkProgram(_t_glLinkProgram));
        _bind("glPixelStorei", p => _r_glPixelStorei = Marshal.GetDelegateForFunctionPointer<D_glPixelStorei>(p), new D_glPixelStorei(_t_glPixelStorei));
        _bind("glPolygonMode", p => _r_glPolygonMode = Marshal.GetDelegateForFunctionPointer<D_glPolygonMode>(p), new D_glPolygonMode(_t_glPolygonMode));
        _bind("glRenderbufferStorage", p => _r_glRenderbufferStorage = Marshal.GetDelegateForFunctionPointer<D_glRenderbufferStorage>(p), new D_glRenderbufferStorage(_t_glRenderbufferStorage));
        _bind("glScissor", p => _r_glScissor = Marshal.GetDelegateForFunctionPointer<D_glScissor>(p), new D_glScissor(_t_glScissor));
        _bind("glShaderSource", p => _r_glShaderSource = Marshal.GetDelegateForFunctionPointer<D_glShaderSource>(p), new D_glShaderSource(_t_glShaderSource));
        _bind("glTexImage2D", p => _r_glTexImage2D = Marshal.GetDelegateForFunctionPointer<D_glTexImage2D>(p), new D_glTexImage2D(_t_glTexImage2D));
        _bind("glTexParameterIiv", p => _r_glTexParameterIiv = Marshal.GetDelegateForFunctionPointer<D_glTexParameterIiv>(p), new D_glTexParameterIiv(_t_glTexParameterIiv));
        _bind("glTexParameterIuiv", p => _r_glTexParameterIuiv = Marshal.GetDelegateForFunctionPointer<D_glTexParameterIuiv>(p), new D_glTexParameterIuiv(_t_glTexParameterIuiv));
        _bind("glTexParameterf", p => _r_glTexParameterf = Marshal.GetDelegateForFunctionPointer<D_glTexParameterf>(p), new D_glTexParameterf(_t_glTexParameterf));
        _bind("glTexParameteri", p => _r_glTexParameteri = Marshal.GetDelegateForFunctionPointer<D_glTexParameteri>(p), new D_glTexParameteri(_t_glTexParameteri));
        _bind("glTexStorage2D", p => _r_glTexStorage2D = Marshal.GetDelegateForFunctionPointer<D_glTexStorage2D>(p), new D_glTexStorage2D(_t_glTexStorage2D));
        _bind("glTexSubImage2D", p => _r_glTexSubImage2D = Marshal.GetDelegateForFunctionPointer<D_glTexSubImage2D>(p), new D_glTexSubImage2D(_t_glTexSubImage2D));
        _bind("glUniform1f", p => _r_glUniform1f = Marshal.GetDelegateForFunctionPointer<D_glUniform1f>(p), new D_glUniform1f(_t_glUniform1f));
        _bind("glUniform1i", p => _r_glUniform1i = Marshal.GetDelegateForFunctionPointer<D_glUniform1i>(p), new D_glUniform1i(_t_glUniform1i));
        _bind("glUniform1ui", p => _r_glUniform1ui = Marshal.GetDelegateForFunctionPointer<D_glUniform1ui>(p), new D_glUniform1ui(_t_glUniform1ui));
        _bind("glUniform3f", p => _r_glUniform3f = Marshal.GetDelegateForFunctionPointer<D_glUniform3f>(p), new D_glUniform3f(_t_glUniform3f));
        _bind("glUniform4f", p => _r_glUniform4f = Marshal.GetDelegateForFunctionPointer<D_glUniform4f>(p), new D_glUniform4f(_t_glUniform4f));
        _bind("glUniformMatrix4fv", p => _r_glUniformMatrix4fv = Marshal.GetDelegateForFunctionPointer<D_glUniformMatrix4fv>(p), new D_glUniformMatrix4fv(_t_glUniformMatrix4fv));
        _bind("glUseProgram", p => _r_glUseProgram = Marshal.GetDelegateForFunctionPointer<D_glUseProgram>(p), new D_glUseProgram(_t_glUseProgram));
        _bind("glVertexAttribDivisor", p => _r_glVertexAttribDivisor = Marshal.GetDelegateForFunctionPointer<D_glVertexAttribDivisor>(p), new D_glVertexAttribDivisor(_t_glVertexAttribDivisor));
        _bind("glVertexAttribIPointer", p => _r_glVertexAttribIPointer = Marshal.GetDelegateForFunctionPointer<D_glVertexAttribIPointer>(p), new D_glVertexAttribIPointer(_t_glVertexAttribIPointer));
        _bind("glVertexAttribPointer", p => _r_glVertexAttribPointer = Marshal.GetDelegateForFunctionPointer<D_glVertexAttribPointer>(p), new D_glVertexAttribPointer(_t_glVertexAttribPointer));
        _bind("glViewport", p => _r_glViewport = Marshal.GetDelegateForFunctionPointer<D_glViewport>(p), new D_glViewport(_t_glViewport));
    }

    private static void _bind(string name, Action<IntPtr> setReal, Delegate thunk)
    {
        IntPtr real = _real!(name);
        // A null pointer means the driver does not export it - a GLES context missing
        // a desktop-only call, say. Leave it untraced rather than binding a null.
        if (real == IntPtr.Zero) return;
        setReal(real);
        _keepAlive.Add(thunk);
        _thunks[name] = Marshal.GetFunctionPointerForDelegate(thunk);
    }
}
