#!/usr/bin/env bash
# Generated by docs-domain-triage. Review before running.
# Moves 92 of 96 docs. The 4 in REVIEW.md 'Needs your decision' are deliberately excluded.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

# --- create target tree ---
mkdir -p docs/debug-infra/archive
mkdir -p docs/debug-infra/docs
mkdir -p docs/debug-infra/plans/todo
mkdir -p docs/main/archive
mkdir -p docs/main/docs
mkdir -p docs/main/docs/architecture
mkdir -p docs/main/docs/build
mkdir -p docs/main/docs/persistence
mkdir -p docs/main/docs/platforms
mkdir -p docs/main/docs/quest
mkdir -p docs/main/plans/done
mkdir -p docs/navigation/archive
mkdir -p docs/navigation/docs
mkdir -p docs/navigation/plans/done
mkdir -p docs/tale/archive
mkdir -p docs/tale/docs
mkdir -p docs/tale/docs/concepts
mkdir -p docs/tale/docs/design
mkdir -p docs/tale/docs/phases
mkdir -p docs/tale/docs/tests
mkdir -p docs/tale/plans/done
mkdir -p docs/tale/plans/proposed
mkdir -p docs/testing/docs
mkdir -p docs/testing/plans/done
mkdir -p docs/world-gen/archive
mkdir -p docs/world-gen/docs
mkdir -p docs/world-gen/plans/proposed

# --- move files (git mv preserves history) ---

# ===== debug-infra (4 files) =====
git mv docs/DEBUG-FILTER-AUDIT.md docs/debug-infra/archive/DEBUG-FILTER-AUDIT.md
git mv docs/roadmap/done/DEBUG-FILTER-ARCHITECTURE.md docs/debug-infra/docs/ARCHITECTURE.md
git mv docs/DEBUG-FILTER-MIGRATION-CHECKLIST.md docs/debug-infra/plans/todo/MIGRATION-CHECKLIST.md
git mv docs/roadmap/planned/SYSTEMATIC-DEBUG-FILTER-MIGRATION.md docs/debug-infra/plans/todo/SYSTEMATIC-MIGRATION.md

# ===== main (12 files) =====
git mv docs/FRAME_NUMBER_INVESTIGATION.md docs/main/archive/FRAME_NUMBER_INVESTIGATION.md
git mv docs/PROCESS_DOCS.md docs/main/docs/PROCESS_DOCS.md
git mv docs/ARCHITECTURE/README.md docs/main/docs/architecture/README.md
git mv docs/ARCHITECTURE/RENDERING.md docs/main/docs/architecture/RENDERING.md
git mv docs/SYSTEMS/BUILD/PIPELINE.md docs/main/docs/build/PIPELINE.md
git mv docs/SYSTEMS/PERSISTENCE/LITEDB.md docs/main/docs/persistence/LITEDB.md
git mv docs/SYSTEMS/PLATFORMS/ANDROID.md docs/main/docs/platforms/ANDROID.md
git mv docs/SYSTEMS/QUEST/QUEST_SYSTEM.md docs/main/docs/quest/QUEST_SYSTEM.md
git mv docs/ANIMATION_ASSIMP_VERSION_COMPENSATION.md docs/main/plans/done/ANIMATION-ASSIMP-VERSION-COMPENSATION.md
git mv docs/roadmap/done/PLAYER-NPC-COLLISION-A-LAYER-FIX.md docs/main/plans/done/PLAYER-NPC-COLLISION-A-LAYER-FIX.md
git mv docs/roadmap/done/PLAYER-NPC-COLLISION-B-HAND-ARM-TOGGLE.md docs/main/plans/done/PLAYER-NPC-COLLISION-B-HAND-ARM-TOGGLE.md
git mv docs/roadmap/done/PLAYER-NPC-COLLISION-C-PUSH-ASIDE.md docs/main/plans/done/PLAYER-NPC-COLLISION-C-PUSH-ASIDE.md

# ===== navigation (11 files) =====
git mv docs/roadmap/PHASE-B-COMPLETION.md docs/navigation/archive/PHASE-B-COMPLETION.md
git mv docs/roadmap/PHASE-C-COMPLETION.md docs/navigation/archive/PHASE-C-COMPLETION.md
git mv docs/roadmap/PHASE-D-PROGRESS.md docs/navigation/archive/PHASE-D-PROGRESS.md
git mv docs/roadmap/proposed/PIPES-FLOW-BASED-MOVEMENT.md docs/navigation/archive/PIPES-FLOW-BASED-MOVEMENT.md
git mv docs/tale/phases/PHASE_D.md docs/navigation/docs/MULTI-OBJECTIVE-ROUTING.md
git mv docs/roadmap/done/IMPLEMENTATION-PLAN-NAVIGATION-SYSTEM.md docs/navigation/plans/done/IMPLEMENTATION-PLAN-NAVIGATION-SYSTEM.md
git mv docs/roadmap/proposed/NAVMAP-TRANSPORTATION-GRAPHS.md docs/navigation/plans/done/NAVMAP-TRANSPORTATION-GRAPHS.md
git mv docs/roadmap/proposed/NAVMESH-PATHFINDING-TALE-NPCS.md docs/navigation/plans/done/NAVMESH-PATHFINDING-TALE-NPCS.md
git mv docs/roadmap/proposed/IMPLEMENTATION-PLAN-PHASE-A-FOUNDATION.md docs/navigation/plans/done/PHASE-A-FOUNDATION.md
git mv docs/roadmap/proposed/IMPLEMENTATION-PLAN-PHASE-B-FLOW.md docs/navigation/plans/done/PHASE-B-FLOW.md
git mv docs/roadmap/proposed/IMPLEMENTATION-PLAN-PHASE-C-DYNAMICS.md docs/navigation/plans/done/PHASE-C-DYNAMICS.md

# ===== tale (55 files) =====
git mv docs/ANALYSIS_NPCs_STUCK_AND_TIMING.md docs/tale/archive/ANALYSIS_NPCs_STUCK_AND_TIMING.md
git mv docs/tale/TALE_ABSTRACTION_INVENTORY.md docs/tale/archive/TALE_ABSTRACTION_INVENTORY.md
git mv docs/TALE_TEST_INFRASTRUCTURE.md docs/tale/archive/TALE_TEST_INFRASTRUCTURE.md
git mv docs/tale/TALE_TEST_SCRIPTS_PHASES_1_2_4_5_SKELETON.md docs/tale/archive/TALE_TEST_SCRIPTS_PHASES_1_2_4_5_SKELETON.md
git mv docs/tale/TALE_TEST_SCRIPTS_PHASE_0_SKELETON.md docs/tale/archive/TALE_TEST_SCRIPTS_PHASE_0_SKELETON.md
git mv docs/TIMING_RECOMMENDATIONS.md docs/tale/archive/TIMING_RECOMMENDATIONS.md
git mv docs/tale/TALE_ARCHITECTURE.md docs/tale/docs/ARCHITECTURE.md
git mv docs/tale/TALE_CONCEPT.md docs/tale/docs/CONCEPT.md
git mv docs/tale/OVERVIEW.md docs/tale/docs/OVERVIEW.md
git mv docs/PROCESS_TALE.md docs/tale/docs/PROCESS_TALE.md
git mv docs/tale/README.md docs/tale/docs/README.md
git mv docs/tale/REFERENCE.md docs/tale/docs/REFERENCE.md
git mv docs/tale/concepts/NARRATION.md docs/tale/docs/concepts/NARRATION.md
git mv docs/tale/design/NPC_COMMUTING.md docs/tale/docs/design/NPC_COMMUTING.md
git mv docs/tale/design/NPC_STORIES.md docs/tale/docs/design/NPC_STORIES.md
git mv docs/tale/design/STRATEGY_ARCHITECTURE.md docs/tale/docs/design/STRATEGY_ARCHITECTURE.md
git mv docs/tale/phases/PHASE_0A.md docs/tale/docs/phases/PHASE_0A.md
git mv docs/tale/phases/PHASE_0B.md docs/tale/docs/phases/PHASE_0B.md
git mv docs/tale/phases/PHASE_0C.md docs/tale/docs/phases/PHASE_0C.md
git mv docs/tale/phases/PHASE_1.md docs/tale/docs/phases/PHASE_1.md
git mv docs/tale/phases/PHASE_2.md docs/tale/docs/phases/PHASE_2.md
git mv docs/tale/phases/PHASE_2_STRATEGIES.md docs/tale/docs/phases/PHASE_2_STRATEGIES.md
git mv docs/tale/phases/PHASE_3.md docs/tale/docs/phases/PHASE_3.md
git mv docs/tale/phases/PHASE_4.md docs/tale/docs/phases/PHASE_4.md
git mv docs/tale/phases/PHASE_5.md docs/tale/docs/phases/PHASE_5.md
git mv docs/tale/phases/PHASE_6.md docs/tale/docs/phases/PHASE_6.md
git mv docs/tale/phases/PHASE_7.md docs/tale/docs/phases/PHASE_7.md
git mv docs/tale/phases/PHASE_8.md docs/tale/docs/phases/PHASE_8.md
git mv docs/tale/phases/PHASE_D_SOCIAL.md docs/tale/docs/phases/PHASE_D_SOCIAL.md
git mv docs/tale/phases/PHASE_E_SOCIAL.md docs/tale/docs/phases/PHASE_E_SOCIAL.md
git mv docs/tale/TALE_TESTING_FRAMEWORK.md docs/tale/docs/tests/FRAMEWORK.md
git mv docs/tale/tests/PHASE_0.md docs/tale/docs/tests/PHASE_0.md
git mv docs/tale/tests/PHASE_1.md docs/tale/docs/tests/PHASE_1.md
git mv docs/tale/tests/PHASE_2.md docs/tale/docs/tests/PHASE_2.md
git mv docs/tale/tests/PHASE_3.md docs/tale/docs/tests/PHASE_3.md
git mv docs/tale/tests/PHASE_4.md docs/tale/docs/tests/PHASE_4.md
git mv docs/tale/tests/PHASE_5.md docs/tale/docs/tests/PHASE_5.md
git mv docs/tale/tests/PHASE_6.md docs/tale/docs/tests/PHASE_6.md
git mv docs/tale/tests/PHASE_7.md docs/tale/docs/tests/PHASE_7.md
git mv docs/tale/tests/PHASE_C.md docs/tale/docs/tests/PHASE_C.md
git mv docs/tale/tests/QUICK_START.md docs/tale/docs/tests/QUICK_START.md
git mv docs/tale/tests/STRATEGY.md docs/tale/docs/tests/STRATEGY.md
git mv docs/tale/TALE_TEST_PLAN.md docs/tale/docs/tests/TEST_PLAN.md
git mv docs/tale/concepts/INTERACTIONS.md docs/tale/plans/done/INTERACTION-TYPE-REGISTRY.md
git mv docs/roadmap/proposed/PHASE-C1-INFRASTRUCTURE.md docs/tale/plans/done/PHASE-C1-INFRASTRUCTURE.md
git mv docs/roadmap/done/PHASE-C2-STORYLET-DIALOGUE.md docs/tale/plans/done/PHASE-C2-STORYLET-DIALOGUE.md
git mv docs/tale/phases/PHASE_7B.md docs/tale/plans/done/PHASE_7B-BUILDING-ROLE-TAGGING.md
git mv docs/tale/phases/PHASE_C.md docs/tale/plans/done/PHASE_C-NPC-CONVERSATIONS.md
git mv docs/tale/concepts/ROLES.md docs/tale/plans/done/ROLE-REGISTRY.md
git mv docs/roadmap/proposed/TALE-NPC-CONVERSATION-SYSTEM.md docs/tale/plans/done/TALE-NPC-CONVERSATION-SYSTEM-C1-C4.md
git mv docs/roadmap/done/TALE-SOCIAL-PHASES.md docs/tale/plans/done/TALE-SOCIAL-PHASE-D-SCENARIOS.md
git mv docs/roadmap/done/IMPLEMENTATION-PLAN-TALE-SOCIAL-PHASE-E.md docs/tale/plans/done/TALE-SOCIAL-PHASE-E.md
git mv docs/tale/TALE_IMPLEMENTATION_PLAN.md docs/tale/plans/done/TALE_IMPLEMENTATION_PLAN.md
git mv docs/roadmap/proposed/PHASE-C5-AMBIENT-NPC-DIALOGUE.md docs/tale/plans/proposed/PHASE-C5-AMBIENT-NPC-DIALOGUE.md
git mv docs/roadmap/proposed/PHASE-C6-STORYLINE-CONVERSATION-TREES.md docs/tale/plans/proposed/PHASE-C6-STORYLINE-CONVERSATION-TREES.md

# ===== testing (7 files) =====
git mv docs/SYSTEMS/NARRATION/EXPECT_ENGINE.md docs/testing/docs/EXPECT_ENGINE.md
git mv docs/SYSTEMS/NARRATION/EXPECT_IMPLEMENTATION.md docs/testing/docs/EXPECT_IMPLEMENTATION.md
git mv docs/TESTING/README.md docs/testing/docs/README.md
git mv docs/RUN_TESTS_GUIDE.md docs/testing/docs/RUN_TESTS_GUIDE.md
git mv docs/TESTING/TESTBED.md docs/testing/docs/TESTBED.md
git mv docs/TESTING/TESTING_STRATEGY.md docs/testing/docs/TESTING_STRATEGY.md
git mv docs/TESTING/TIERS.md docs/testing/plans/done/TIERS.md

# ===== world-gen (3 files) =====
git mv docs/SYSTEMS/WORLD_GEN/LSYSTEM_EDITOR.md docs/world-gen/archive/LSYSTEM_EDITOR.md
git mv docs/SYSTEMS/WORLD_GEN/LSYSTEM.md docs/world-gen/docs/LSYSTEM.md
git mv docs/SYSTEMS/WORLD_GEN/FRAGMENT_OPERATORS.md docs/world-gen/plans/proposed/BIRD-SWARM-OPERATOR.md

echo 'Moved. Next: python docs/_migration/apply-status-headers.py && python docs/_migration/fix-links.py'
